### ISSUE TITLE
Unable to load the data - Issue in Metadata.csv

### ISSUE THREAD

**Issue by kainat-altaf-cau** [lucascesarfd/underwater_snd#3]
Hello,

Thank you for your work. I have one concern while loading the data. In 

> **_inclusion_2000_exclusion_4000/train/metadata.csv_**

if you look at records with path 

> **_./vessel/167.wav_**

you will see the class label is **Cargo**. However, there is no 167.wav record in the **train/cargo** folder. Interestingly, there is 167.wav in the **train/background** folder.

Additionally, I am facing the same issue(but with different file names) in other data folders too i.e. inclusion_3000_exclusion_5000, inclusion_4000_exclusion_6000.

So either the metadata file is incorrect or the data distribution into folders is improper. Can you please recheck and help me resolve this?  If you have a working copy of the dataset that you are using for this pipeline, please share it here. 

I really appreciate any help you can provide.

**Comment by psmskelton** [comment]
@kainat-altaf-cau - If I had to take a guess (long time since I wrote the foundation of this work), this is possibly caused by ONC transcoding their .WAV data lake into .FLAC files. The metadata pipeline would be identifying a hydrophone deployment and inc./exc. scenario, but the corresponding .WAV file may not be available.

Why didn't we write this to handle .WAV and .FLAC? Because ONC started the .FLAC transcode process sometime after our papers were published.

The dataset should be attached to the paper, but is likely behind an IEEE paywall. Nothing we can really do about that, unfortunately. The joys of publication rights. 

I will see if I can find time to update both the DeeperShip repo and this repo to "work" with the updated ONC data lake, but I cannot guarantee timing.

**Comment by kainat-altaf-cau** [comment]
@philboske Thank you for your reply. 

The issue you mention should happen if I use [ONC Dataset Generation Pipeline](https://github.com/lucascesarfd/onc_dataset) to generate the data. However, I am using this dataset [VTUAD](https://ieee-dataport.org/documents/vtuad-vessel-type-underwater-acoustic-data ) which should work directly with your code. Please correct me if I am wrong. Maybe I am missing any point in this.

**Comment by psmskelton** [comment]
@kainat-altaf-cau - Ahh, yes, my apologies. That doesn't make much sense. I'll have a look at it when I get a chance.

**Comment by lucascesarfd** [comment]
Hi @kainat-altaf-cau 

The metadata on VTUAD was incorrect. Thanks for noticing. It was corrected and uploaded at [VTUAD homepage](https://ieee-dataport.org/documents/vtuad-vessel-type-underwater-acoustic-data).

The path column wasn't needed and was causing misunderstanding, so it was removed. The column which indicates the correct file is the file_index column. (refer to [vtuad.py file](https://github.com/lucascesarfd/underwater_snd/blob/master/nauta/dataset/vtuad.py#L52) for an example).
